"""Markdown projection layer for structured memory items."""

import logging
import os
import tempfile
from datetime import datetime
from pathlib import Path
from typing import Optional

from core.memory.memory_schema import MemoryItem, MemoryType

logger = logging.getLogger(__name__)

_HEADER_TEMPLATE = (
    "<!-- Generated by Lobuddy MemoryService at {timestamp}.\n"
    "     SQLite memory_item is authoritative. DO NOT EDIT this file directly.\n"
    "     Changes will be overwritten on next projection refresh. -->\n\n"
)


class MemoryProjection:
    """Projects SQLite memory items into markdown files for human readability and nanobot compatibility."""

    def __init__(self, data_dir: Path, workspace_path: Path) -> None:
        self.data_dir = data_dir
        self.memory_dir = data_dir / "memory"
        self.workspace_path = workspace_path

    def project_all(self, items: list[MemoryItem]) -> None:
        self.memory_dir.mkdir(parents=True, exist_ok=True)
        self._project_user_profile(items)
        self._project_system_profile(items)
        self._project_project_memory(items)
        self._project_to_workspace(items)

    def _project_user_profile(self, items: list[MemoryItem]) -> None:
        user_items = [i for i in items if i.memory_type == MemoryType.USER_PROFILE and i.status.value == "active"]
        if not user_items:
            return
        grouped: dict[str, list[str]] = {}
        for item in user_items:
            grouped.setdefault(item.title or "Basic Notes", []).append(item.content)
        lines: list[str] = [self._generated_header()]
        for title, contents in sorted(grouped.items()):
            lines.extend([f"## {self._sanitize_line(title)}", ""])
            for content in contents:
                lines.append(f"- {self._sanitize_line(content)}")
            lines.append("")
        content = "\n".join(lines).rstrip() + "\n"
        self._write_atomic(self.memory_dir / "USER.md", content)

    def _project_system_profile(self, items: list[MemoryItem]) -> None:
        system_items = [i for i in items if i.memory_type == MemoryType.SYSTEM_PROFILE and i.status.value == "active"]
        if not system_items:
            return
        lines = [self._generated_header(), "## System Behavior", ""]
        for item in system_items:
            lines.append(f"- {self._sanitize_line(item.content)}")
        content = "\n".join(lines) + "\n"
        self._write_atomic(self.memory_dir / "SYSTEM.md", content)

    def _project_project_memory(self, items: list[MemoryItem]) -> None:
        project_items = [i for i in items if i.memory_type == MemoryType.PROJECT_MEMORY and i.status.value == "active"]
        if not project_items:
            return
        scopes: dict[str, list[str]] = {}
        for item in project_items:
            scopes.setdefault(item.scope, []).append(item.content)
        lines: list[str] = [self._generated_header()]
        for scope, contents in sorted(scopes.items()):
            lines.append(f"## {scope}")
            lines.append("")
            for c in contents:
                lines.append(f"- {self._sanitize_line(c)}")
            lines.append("")
        project_content = "\n".join(lines)
        self._write_atomic(self.memory_dir / "PROJECT.md", project_content)
        workspace_memory = self.workspace_path / "memory"
        workspace_memory.mkdir(parents=True, exist_ok=True)
        self._write_atomic(workspace_memory / "MEMORY.md", project_content)

    def _project_to_workspace(self, items: list[MemoryItem]) -> None:
        user_items = [i for i in items if i.memory_type == MemoryType.USER_PROFILE and i.status.value == "active"]
        if user_items:
            grouped: dict[str, list[str]] = {}
            for item in user_items:
                grouped.setdefault(item.title or "Basic Information", []).append(item.content)
            lines: list[str] = [self._generated_header()]
            for title, contents in sorted(grouped.items()):
                workspace_title = "Basic Information" if title == "Basic Notes" else title
                lines.extend([f"## {self._sanitize_line(workspace_title)}", ""])
                for content in contents:
                    lines.append(f"- {self._sanitize_line(content)}")
                lines.append("")
            self._write_atomic(self.workspace_path / "USER.md", "\n".join(lines).rstrip() + "\n")
        system_items = [i for i in items if i.memory_type == MemoryType.SYSTEM_PROFILE and i.status.value == "active"]
        if system_items:
            lines = [self._generated_header(), "## Personality", ""]
            for item in system_items:
                lines.append(f"- {self._sanitize_line(item.content)}")
            self._write_atomic(self.workspace_path / "SOUL.md", "\n".join(lines) + "\n")
        project_items = [i for i in items if i.memory_type == MemoryType.PROJECT_MEMORY and i.status.value == "active"]
        if project_items:
            scopes: dict[str, list[str]] = {}
            for item in project_items:
                scopes.setdefault(item.scope, []).append(item.content)
            lines = [self._generated_header()]
            for scope, contents in sorted(scopes.items()):
                lines.append(f"## {scope}")
                lines.append("")
                for c in contents:
                    lines.append(f"- {self._sanitize_line(c)}")
                lines.append("")
            workspace_memory = self.workspace_path / "memory"
            workspace_memory.mkdir(parents=True, exist_ok=True)
            self._write_atomic(workspace_memory / "MEMORY.md", "\n".join(lines))

    @staticmethod
    def _write_atomic(path: Path, content: str) -> None:
        path.parent.mkdir(parents=True, exist_ok=True)
        fd, tmp = tempfile.mkstemp(dir=path.parent, prefix=".mem_proj_", suffix=".tmp")
        try:
            with os.fdopen(fd, "w", encoding="utf-8") as f:
                _ = f.write(content)
            os.replace(tmp, path)
        except BaseException:
            try:
                os.unlink(tmp)
            except OSError:
                pass
            raise

    @staticmethod
    def _generated_header() -> str:
        return _HEADER_TEMPLATE.format(timestamp=datetime.now().isoformat())

    @staticmethod
    def _sanitize_line(text: str) -> str:
        import re

        patterns = [
            re.compile(r"sk-[a-zA-Z0-9]{20,}"),
            re.compile(r"ghp_[a-zA-Z0-9]{36}"),
            re.compile(r"xoxb-[a-zA-Z0-9-]+"),
            re.compile(r"Bearer\s+[a-zA-Z0-9._-]+"),
            re.compile(r"[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}"),
        ]
        for pat in patterns:
            text = pat.sub("[REDACTED]", text)
        return text
