"""Phase 1 verification tests for 5.3 Memory System Upgrade.

Covers:
  - P0-2: Projection headers + MEMORY.md projection
  - P0-3: Dream command interception
  - P1-2: Skill disable/archive file cleanup
  - P1-3: SkillManager injection
  - P0-1a: MemoryWriteGateway skeleton
"""

import json
import os
import re
import uuid
from datetime import datetime
from pathlib import Path

import pytest

from core.config import Settings
from core.memory.memory_schema import (
    MemoryItem,
    MemoryPatch,
    MemoryPatchItem,
    MemoryPatchAction,
    MemoryType,
    MemoryStatus,
)
from core.storage.db import Database


# ─────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────

def _make_settings(tmp_path: Path, **kwargs) -> Settings:
    return Settings(
        llm_api_key="test",
        data_dir=tmp_path / "data",
        logs_dir=tmp_path / "logs",
        workspace_path=tmp_path / "workspace",
        memory_enable_migration=False,
        **kwargs,
    )


def _make_memory_service(tmp_path: Path, **kwargs):
    from core.memory.memory_repository import MemoryRepository
    from core.memory.memory_service import MemoryService

    settings = _make_settings(tmp_path, **kwargs)
    db = Database(settings)
    repo = MemoryRepository(db)
    return MemoryService(settings, repo)


def _make_skill_manager(tmp_path: Path):
    from core.skills.skill_manager import SkillManager

    settings = _make_settings(tmp_path)
    db = Database(settings)
    return SkillManager(settings, db=db)


# ─────────────────────────────────────────────────────────────────
# P0-2: Projection headers + MEMORY.md projection
# ─────────────────────────────────────────────────────────────────

_HEADER_PATTERN = re.compile(
    r"<!-- Generated by Lobuddy MemoryService at \d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d+\.\s+"
    r"SQLite memory_item is authoritative\. DO NOT EDIT"
)


class TestProjectionHeaders:
    """Verify that all projection files have the generated-by header."""

    def test_data_user_md_has_header(self, tmp_path: Path):
        service = _make_memory_service(tmp_path)
        service.save_memory(MemoryItem(
            id="u1", memory_type=MemoryType.USER_PROFILE,
            content="User likes Python", title="Basic Notes",
        ))
        user_md = tmp_path / "data" / "memory" / "USER.md"
        assert user_md.exists(), f"{user_md} should exist"
        content = user_md.read_text(encoding="utf-8")
        assert _HEADER_PATTERN.search(content), (
            f"USER.md should contain generated-by header. Content: {content[:200]}"
        )

    def test_data_system_md_has_header(self, tmp_path: Path):
        service = _make_memory_service(tmp_path, pet_name="TestPet")
        system_md = tmp_path / "data" / "memory" / "SYSTEM.md"
        # Bootstrap creates system profile, which triggers projection
        assert system_md.exists(), f"{system_md} should exist"
        content = system_md.read_text(encoding="utf-8")
        assert _HEADER_PATTERN.search(content), (
            f"SYSTEM.md should contain generated-by header. Content: {content[:200]}"
        )

    def test_data_project_md_has_header(self, tmp_path: Path):
        service = _make_memory_service(tmp_path)
        service.save_memory(MemoryItem(
            id="p1", memory_type=MemoryType.PROJECT_MEMORY,
            content="Lobuddy uses SQLite", scope="lobuddy",
        ))
        project_md = tmp_path / "data" / "memory" / "PROJECT.md"
        assert project_md.exists(), f"{project_md} should exist"
        content = project_md.read_text(encoding="utf-8")
        assert _HEADER_PATTERN.search(content), (
            f"PROJECT.md should contain generated-by header. Content: {content[:200]}"
        )

    def test_workspace_user_md_has_header(self, tmp_path: Path):
        service = _make_memory_service(tmp_path)
        service.save_memory(MemoryItem(
            id="u1", memory_type=MemoryType.USER_PROFILE,
            content="User likes Python", title="Basic Notes",
        ))
        workspace_user = tmp_path / "workspace" / "USER.md"
        assert workspace_user.exists(), f"{workspace_user} should exist"
        content = workspace_user.read_text(encoding="utf-8")
        assert _HEADER_PATTERN.search(content), (
            f"workspace/USER.md should contain generated-by header"
        )

    def test_workspace_soul_md_has_header(self, tmp_path: Path):
        service = _make_memory_service(tmp_path, pet_name="TestPet")
        workspace_soul = tmp_path / "workspace" / "SOUL.md"
        assert workspace_soul.exists(), f"{workspace_soul} should exist"
        content = workspace_soul.read_text(encoding="utf-8")
        assert _HEADER_PATTERN.search(content), (
            f"workspace/SOUL.md should contain generated-by header"
        )


class TestMemoryMdProjection:
    """Verify that project_memory is projected to workspace/memory/MEMORY.md."""

    def test_memory_md_created(self, tmp_path: Path):
        service = _make_memory_service(tmp_path)
        service.save_memory(MemoryItem(
            id="p1", memory_type=MemoryType.PROJECT_MEMORY,
            content="Lobuddy project v5.3", scope="lobuddy",
        ))
        memory_md = tmp_path / "workspace" / "memory" / "MEMORY.md"
        assert memory_md.exists(), (
            f"workspace/memory/MEMORY.md should exist. Files in workspace/memory/: "
            f"{list((tmp_path / 'workspace' / 'memory').iterdir()) if (tmp_path / 'workspace' / 'memory').exists() else 'DIR_NOT_FOUND'}"
        )

    def test_memory_md_contains_project_content(self, tmp_path: Path):
        service = _make_memory_service(tmp_path)
        service.save_memory(MemoryItem(
            id="p1", memory_type=MemoryType.PROJECT_MEMORY,
            content="Lobuddy project v5.3", scope="lobuddy",
        ))
        memory_md = tmp_path / "workspace" / "memory" / "MEMORY.md"
        content = memory_md.read_text(encoding="utf-8")
        assert "Lobuddy project v5.3" in content
        assert _HEADER_PATTERN.search(content), "MEMORY.md should have generated header"

    def test_memory_md_syncs_with_project_md(self, tmp_path: Path):
        service = _make_memory_service(tmp_path)
        service.save_memory(MemoryItem(
            id="p1", memory_type=MemoryType.PROJECT_MEMORY,
            content="Sync test content", scope="test",
        ))
        data_project = tmp_path / "data" / "memory" / "PROJECT.md"
        workspace_memory = tmp_path / "workspace" / "memory" / "MEMORY.md"
        # Both should exist and contain the same project content
        assert data_project.exists()
        assert workspace_memory.exists()
        dp = data_project.read_text(encoding="utf-8")
        wm = workspace_memory.read_text(encoding="utf-8")
        assert "Sync test content" in dp
        assert "Sync test content" in wm


# ─────────────────────────────────────────────────────────────────
# P0-3: Dream command interception
# ─────────────────────────────────────────────────────────────────

class TestDreamCommandBlocking:
    """Verify that /dream commands are intercepted in nanobot_adapter."""

    def test_preflight_method_exists(self):
        """Verify _preflight_lobuddy_memory_boundary method exists on NanobotAdapter."""
        from core.agent.nanobot_adapter import NanobotAdapter

        assert hasattr(NanobotAdapter, "_preflight_lobuddy_memory_boundary"), (
            "NanobotAdapter must have _preflight_lobuddy_memory_boundary method"
        )

    def test_preflight_blocks_dream(self):
        from core.agent.nanobot_adapter import NanobotAdapter, AgentResult
        from core.config import Settings

        adapter = NanobotAdapter(Settings(llm_api_key="test"))
        result = adapter._preflight_lobuddy_memory_boundary("/dream")
        assert result is not None, "/dream should be blocked"
        assert isinstance(result, AgentResult)
        assert result.success is False
        assert "Dream" in result.error_message or "dream" in result.summary.lower()

    def test_preflight_blocks_dream_log(self):
        from core.agent.nanobot_adapter import NanobotAdapter
        from core.config import Settings

        adapter = NanobotAdapter(Settings(llm_api_key="test"))
        result = adapter._preflight_lobuddy_memory_boundary("/dream-log")
        assert result is not None, "/dream-log should be blocked"

    def test_preflight_blocks_dream_restore(self):
        from core.agent.nanobot_adapter import NanobotAdapter
        from core.config import Settings

        adapter = NanobotAdapter(Settings(llm_api_key="test"))
        result = adapter._preflight_lobuddy_memory_boundary("/dream-restore")
        assert result is not None, "/dream-restore should be blocked"

    def test_preflight_blocks_dream_with_args(self):
        from core.agent.nanobot_adapter import NanobotAdapter
        from core.config import Settings

        adapter = NanobotAdapter(Settings(llm_api_key="test"))
        result = adapter._preflight_lobuddy_memory_boundary("/dream --force")
        assert result is not None, "/dream with args should be blocked"

    def test_preflight_allows_normal_messages(self):
        from core.agent.nanobot_adapter import NanobotAdapter
        from core.config import Settings

        adapter = NanobotAdapter(Settings(llm_api_key="test"))
        result = adapter._preflight_lobuddy_memory_boundary("Hello, how are you?")
        assert result is None, "Normal messages should not be blocked"
        result2 = adapter._preflight_lobuddy_memory_boundary("I had a dream last night")
        assert result2 is None, "Messages containing 'dream' as a word should not be blocked"

    def test_dream_constant_exists(self):
        from core.agent.nanobot_adapter import _DREAM_COMMANDS

        assert isinstance(_DREAM_COMMANDS, tuple)
        assert "/dream" in _DREAM_COMMANDS
        assert "/dream-log" in _DREAM_COMMANDS
        assert "/dream-restore" in _DREAM_COMMANDS

    def test_preflight_respects_memory_block_setting(self):
        from core.agent.nanobot_adapter import NanobotAdapter
        from core.config import Settings

        adapter_enabled = NanobotAdapter(Settings(
            llm_api_key="test", memory_block_dream_commands=True,
        ))
        assert adapter_enabled._preflight_lobuddy_memory_boundary("/dream") is not None

        adapter_disabled = NanobotAdapter(Settings(
            llm_api_key="test", memory_block_dream_commands=False,
        ))
        assert adapter_disabled._preflight_lobuddy_memory_boundary("/dream") is None, (
            "Dream should NOT be blocked when memory_block_dream_commands=False"
        )

    def test_tracker_respects_block_setting(self):
        from core.agent.nanobot_adapter import _ToolTracker

        tracker_enabled = _ToolTracker(block_dream_commands=True)
        assert tracker_enabled.block_dream_commands is True

        tracker_disabled = _ToolTracker(block_dream_commands=False)
        assert tracker_disabled.block_dream_commands is False


# ─────────────────────────────────────────────────────────────────
# P1-2: Skill disable/archive file cleanup
# ─────────────────────────────────────────────────────────────────

class TestSkillFileCleanup:
    """Verify disabled/archived skills have their workspace files removed."""

    def test_disable_skill_removes_file(self, tmp_path: Path):
        from core.skills.skill_schema import SkillRecord, SkillStatus

        mgr = _make_skill_manager(tmp_path)
        record = SkillRecord(
            id=str(uuid.uuid4()),
            name="test-skill",
            path="",
            description="Test skill",
        )
        created = mgr.create_skill(record, "# Test Skill\n\nTest content")
        assert Path(created.path).exists(), "Skill file should exist after creation"

        mgr.disable_skill(created.id)
        assert not Path(created.path).exists(), (
            "Skill file should be removed after disable"
        )

    def test_archive_skill_removes_original_file(self, tmp_path: Path):
        from core.skills.skill_schema import SkillRecord, SkillStatus

        mgr = _make_skill_manager(tmp_path)
        record = SkillRecord(
            id=str(uuid.uuid4()),
            name="archive-test",
            path="",
            description="Archive test skill",
        )
        created = mgr.create_skill(record, "# Archive Skill\n\nContent")
        original_path = Path(created.path)
        assert original_path.exists()

        mgr.archive_skill(created.id)
        assert not original_path.exists(), (
            "Original skill file should be removed after archive"
        )
        # Archive copy should exist
        archive_file = mgr._archive_dir / f"{created.name}_v{created.version}.md"
        assert archive_file.exists(), "Archive copy should exist"

    def test_disable_skill_cleans_empty_dir(self, tmp_path: Path):
        from core.skills.skill_schema import SkillRecord

        mgr = _make_skill_manager(tmp_path)
        record = SkillRecord(
            id=str(uuid.uuid4()),
            name="cleanup-test",
            path="",
            description="Cleanup test",
        )
        created = mgr.create_skill(record, "# Cleanup\n\nTest")
        skill_dir = Path(created.path).parent
        assert skill_dir.exists()

        mgr.disable_skill(created.id)
        assert not skill_dir.exists(), (
            "Empty skill directory should be removed after disable"
        )

    def test_active_skill_file_preserved(self, tmp_path: Path):
        from core.skills.skill_schema import SkillRecord, SkillStatus

        mgr = _make_skill_manager(tmp_path)
        record = SkillRecord(
            id=str(uuid.uuid4()),
            name="active-skill",
            path="",
            description="Active skill",
            status=SkillStatus.ACTIVE,
        )
        created = mgr.create_skill(record, "# Active\n\nContent")
        assert Path(created.path).exists(), "Active skill file should exist"
        # Check DB status is active
        loaded = mgr.get_skill(created.id)
        assert loaded is not None
        assert loaded.status == SkillStatus.ACTIVE


# ─────────────────────────────────────────────────────────────────
# P0-1a: MemoryWriteGateway skeleton
# ─────────────────────────────────────────────────────────────────

class TestMemoryWriteGateway:
    """Verify MemoryWriteGateway skeleton exists and conforms to spec."""

    def test_gateway_module_importable(self):
        """Gateway module should be importable without errors."""
        from core.memory.memory_write_gateway import MemoryWriteGateway
        assert MemoryWriteGateway is not None

    def test_models_exist(self):
        """All required Pydantic models should exist."""
        from core.memory.memory_write_gateway import (
            WriteContext,
            WriteResult,
            Rejection,
        )
        assert WriteContext is not None
        assert WriteResult is not None
        assert Rejection is not None

    def test_gateway_instantiable(self, tmp_path: Path):
        """Gateway should be instantiable with MemoryService and Settings."""
        from core.memory.memory_write_gateway import MemoryWriteGateway

        service = _make_memory_service(tmp_path)
        settings = _make_settings(tmp_path)
        gateway = MemoryWriteGateway(service, settings)
        assert gateway is not None
        assert gateway._memory_service is service

    def test_submit_patch_accepts_items(self, tmp_path: Path):
        """submit_patch should apply memory patches through MemoryService."""
        from core.memory.memory_write_gateway import (
            MemoryWriteGateway,
            WriteContext,
            WriteResult,
        )

        service = _make_memory_service(tmp_path)
        settings = _make_settings(tmp_path)
        gateway = MemoryWriteGateway(service, settings)

        import asyncio
        patch = MemoryPatch(items=[
            MemoryPatchItem(
                memory_type=MemoryType.PROJECT_MEMORY,
                action=MemoryPatchAction.ADD,
                content="Gateway test memory",
                confidence=0.9,
                importance=0.7,
            )
        ])
        context = WriteContext(
            source="ai_patch",
            session_id="test-session",
            triggered_by="test",
        )

        async def run():
            return await gateway.submit_patch(patch, context)

        result = asyncio.run(run())
        assert isinstance(result, WriteResult)
        assert len(result.accepted) == 1
        assert result.accepted[0].content == "Gateway test memory"

    def test_submit_identity_memory(self, tmp_path: Path):
        """submit_identity_memory should upsert identity memories."""
        from core.memory.memory_write_gateway import (
            MemoryWriteGateway,
            WriteContext,
        )

        service = _make_memory_service(tmp_path)
        settings = _make_settings(tmp_path)
        gateway = MemoryWriteGateway(service, settings)

        context = WriteContext(
            source="strong_signal",
            session_id="test-session",
            triggered_by="adapter",
        )
        item = gateway.submit_identity_memory(
            memory_type=MemoryType.USER_PROFILE,
            title="Basic Notes",
            content="The user's name is TestUser.",
            context=context,
        )
        assert item is not None
        assert "TestUser" in item.content


# ─────────────────────────────────────────────────────────────────
# Settings / .env
# ─────────────────────────────────────────────────────────────────

class TestPhase1Settings:
    """Verify new 5.3 settings fields exist and have correct defaults."""

    def test_session_search_settings(self):
        settings = Settings(llm_api_key="test")
        assert hasattr(settings, "memory_session_search_enabled")
        assert settings.memory_session_search_enabled is False
        assert settings.memory_session_search_default_scope == "current_session"
        assert settings.memory_session_search_max_result_chars == 300
        assert settings.memory_session_search_total_budget_chars == 1500

    def test_gateway_settings(self):
        settings = Settings(llm_api_key="test")
        assert hasattr(settings, "memory_gateway_min_confidence")
        assert settings.memory_gateway_min_confidence == 0.75
        assert settings.memory_gateway_max_items_per_patch == 8

    def test_hot_context_settings(self):
        settings = Settings(llm_api_key="test")
        assert settings.memory_hot_user_profile_tokens == 500
        assert settings.memory_hot_system_profile_tokens == 300
        assert settings.memory_hot_project_context_tokens == 800

    def test_lint_settings(self):
        settings = Settings(llm_api_key="test")
        assert settings.memory_lint_enabled is True
        assert settings.memory_lint_duplicate_similarity == 0.8
        assert settings.memory_lint_stale_days == 90
        assert settings.memory_lint_low_confidence_days == 30

    def test_dream_block_settings(self):
        settings = Settings(llm_api_key="test")
        assert hasattr(settings, "memory_block_dream_commands")
        assert settings.memory_block_dream_commands is True


# ─────────────────────────────────────────────────────────────────
# Integration: Full Phase 1 flow
# ─────────────────────────────────────────────────────────────────

class TestPhase1Integration:
    """End-to-end: projection → gateway → skill cleanup."""

    def test_project_then_read_memory_from_gateway(self, tmp_path: Path):
        """Write via gateway, verify projection files reflect it."""
        from core.memory.memory_write_gateway import (
            MemoryWriteGateway,
            WriteContext,
        )
        import asyncio

        service = _make_memory_service(tmp_path)
        settings = _make_settings(tmp_path)
        gateway = MemoryWriteGateway(service, settings)

        patch = MemoryPatch(items=[
            MemoryPatchItem(
                memory_type=MemoryType.PROJECT_MEMORY,
                action=MemoryPatchAction.ADD,
                content="Integration test project memory",
                confidence=0.9,
                importance=0.8,
                scope="integration",
            )
        ])
        context = WriteContext(source="ai_patch", triggered_by="test")

        async def run():
            return await gateway.submit_patch(patch, context)

        result = asyncio.run(run())
        assert len(result.accepted) == 1

        # Verify projection files exist and contain the content
        project_md = tmp_path / "data" / "memory" / "PROJECT.md"
        memory_md = tmp_path / "workspace" / "memory" / "MEMORY.md"

        assert project_md.exists(), "PROJECT.md should exist"
        assert memory_md.exists(), "MEMORY.md should exist"

        pm = project_md.read_text(encoding="utf-8")
        mm = memory_md.read_text(encoding="utf-8")
        assert "Integration test project memory" in pm
        assert "Integration test project memory" in mm

    def test_skill_disable_prevents_nanobot_discovery(self, tmp_path: Path):
        """After disable, skill file should NOT exist in workspace/skills/."""
        from core.skills.skill_schema import SkillRecord

        mgr = _make_skill_manager(tmp_path)
        record = SkillRecord(
            id=str(uuid.uuid4()),
            name="test-nanobot-skill",
            path="",
            description="Should be removed",
        )
        created = mgr.create_skill(record, "# Test\n\nContent")
        assert Path(created.path).exists()

        mgr.disable_skill(created.id)

        # Verify the skill file is gone
        assert not Path(created.path).exists()
        # Verify parent directory is cleaned up
        assert not Path(created.path).parent.exists()
